### ISSUE TITLE
Disable caching for retrolite directive

### ISSUE THREAD

**Issue by kolibril13** [jupyterlite/jupyterlite-sphinx#101]
Related to https://github.com/jupyterlite/jupyterlite/issues/1067

When I go to the retro-lite example https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/retrolite.html with a specific notebook (`.. retrolite:: my_notebook.ipynb`), and make some changes, these changes are permanent and there is no way to get back to the original example.
Similar how @agoose77 solved that issue, it would be great to have a similar solution for this jupyterlite-sphinx directive.
https://github.com/jupyterlite/jupyterlite/issues/1067#issuecomment-1523875403

**Comment by agoose77** [comment]
You can already do this with the existing `jupyter-lite.json` configuration. Just place your configuration file in `lite/` relative to your Sphinx directory (or set the `jupyterlite_dir` Sphinx configuration variable): https://github.com/scikit-hep/awkward/blob/main/docs/lite/jupyter-lite.json

**Comment by Carreau** [comment]
Per @agoose77 answer, I believe this can be closed. 

Too keep the number of issues small, I'm going to close. Feel free to comment if this needs reopening, or open an new issue referencing this one if there is no responses.
