### ISSUE TITLE
Show that jupyterlite_dir is expected to be a PosixPath object in docs

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterlite/jupyterlite-sphinx#106]
### Problem

Following https://github.com/scikit-hep/pyhf/issues/2299 I noticed that `jupyterlite_dir` config option

https://github.com/jupyterlite/jupyterlite-sphinx/blob/83663dbbc6c8734f22c69dae6d510e0242514340/jupyterlite_sphinx/jupyterlite_sphinx.py#L357

is expected to be a `PosixPath` object

https://github.com/jupyterlite/jupyterlite-sphinx/blob/83663dbbc6c8734f22c69dae6d510e0242514340/jupyterlite_sphinx/jupyterlite_sphinx.py#L247-L249

else it can raise a warning of

```
WARNING: The config value `jupyterlite_dir' has type `str', defaults to `PosixPath'.
```

However, in the docs it is show as a `str`:

https://github.com/jupyterlite/jupyterlite-sphinx/blob/83663dbbc6c8734f22c69dae6d510e0242514340/docs/configuration.md?plain=1#L15-L22

### Suggested Improvement

It would be good to avoid warnings at runtime for users, so if the docs can be updated to show usage of a `pathlib.Path` or `os.path` object that would be great.

Related: https://github.com/scikit-hep/pyhf/pull/2300

**Comment by matthewfeickert** [comment]
I guess alternatively it could be converted into a path object in the code if needed, which is probably easier.

**Comment by martinRenou** [comment]
Thank you for opening an issue. 

> I guess alternatively it could be converted into a path object in the code if needed

That sounds reasonable indeed. Would you have time for a PR? Happy to give a review

**Comment by matthewfeickert** [comment]
Resolved by PR https://github.com/jupyterlite/jupyterlite-sphinx/pull/150 as the expected value is changed in [`jupyterlite-sphinx` `v0.13.0`](https://github.com/jupyterlite/jupyterlite-sphinx/releases/tag/v0.13.0) from `PosixPath` to `str`.
