### ISSUE TITLE
Rework the order of "try-example" documentation

### ISSUE THREAD

**Issue by Carreau** [jupyterlite/jupyterlite-sphinx#122]
I think that the way the documentation for "try_examples" is written, it implicitely state that you _must_ include `button_css` and `button_css_hover` when creating a directive. 

I think it would be better to :
- have  minimal example at the top of the page, and
- list all options later in the page. 

At least I think that the option for global CSS should be listed _before_ individual button overwrite. 

I also think that the options for custom css are an anti pattern, We should rely on existing mechanism, that is to say [custom css and/or js file](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html#how-to-add-custom-css-or-javascript-to-sphinx-documentation), and simply document that classes that the button have depending the directive options. 

Having the style be in an actual css file allow all the linting/formatting/ci tools to work, as well as allow feature  like viewport dependant style, that can't be done with inlining css in the conf file.

**Comment by steppi** [comment]
Good suggestion. I'll make the  documentation improvements in a PR together with the update to have button css specified in a css file instead of a config variable in Sphinx's `conf.py`.
