### ISSUE TITLE
Build docs in PRs ?

### ISSUE THREAD

**Issue by Carreau** [jupyterlite/jupyterlite-sphinx#126]
It looks to me that docs are not build in PRs, 
I'm not sure how they are supposed to be build, but locally I had to change a couple of things like `yml` to `yaml` for things to build. 

Maybe we should have a workflow checking that our docs build properly ?

**Comment by martinRenou** [comment]
As far as I understand it is being built, for example with your PR https://github.com/jupyterlite/jupyterlite-sphinx/pull/128 the built doc is https://jupyterlite-sphinx--128.org.readthedocs.build/en/128

**Comment by Carreau** [comment]
Yeah, but in case of failure, you can't see the logs as far as I Can tell.

**Comment by martinRenou** [comment]
In case of failure, it *should* mark the check with a red cross and clicking on it should show you the logs.

**Comment by jtpio** [comment]
> In case of failure, it _should_ mark the check with a red cross and clicking on it should show you the logs.

Yes, for example:

- https://github.com/jupyterlite/jupyterlite-sphinx/pull/102
- https://readthedocs.org/projects/jupyterlite-sphinx/builds/20736130/

**Comment by Carreau** [comment]
Ah, thanks you are right. Feel free to close. I still have the impression that GitHub action is a bit more open into how docs are tested. Can readthedocs full configuration be in a readthedocs.yml file so that we can see how it tests docs ?

**Comment by martinRenou** [comment]
The readthedocs configuration is at the root: https://github.com/jupyterlite/jupyterlite-sphinx/blob/main/.readthedocs.yml
