### ISSUE TITLE
Retrolite directive: show the tree view if there is no Notebook passed as argument

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite-sphinx#13]
Currently we **require** a Notebook passed as argument: 

```rst
.. retrolite:: my_notebook.ipynb
```

We should allow the following notation that would show the tree view:

```rst
.. retrolite::
```

**Comment by jtpio** [comment]
@labdala not sure this would help but maybe you can try with the following if using a `.md` file:

```
```{jupyterlite}
  :width: 100%
  :height: 600px
```
```

Mind opening a new issue otherwise so it's easier to track? Thanks!
