### ISSUE TITLE
Publishing new release

### ISSUE THREAD

**Issue by steppi** [jupyterlite/jupyterlite-sphinx#176]
Opening this issue to ask about publishing a new release so we can get https://github.com/jupyterlite/jupyterlite-sphinx/pull/165 in for opening the jupyterlite window in a new tab. @jtpio, @Carreau, @martinRenou, do any of you have any objections to making a new release now?

**Comment by jtpio** [comment]
Sounds good :+1: 

Maybe a `0.15.0` if it adds a new feature?

**Comment by steppi** [comment]
> Maybe a `0.15.0` if it adds a new feature?

Yes, it seems like it’s worth bumping to `0.15.0`. Thanks!

**Comment by steppi** [comment]
I've gone ahead and made the release.

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by martinRenou** [comment]
Thanks!
