### ISSUE TITLE
Error when used with Jupyter Book: source_suffix '.ipynb' is already registered

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite-sphinx#27]
Running this extension with Jupyter Book (a custom sphinx build), which already has `ipynb` registered as a file type, generates an error when building a book:

```
Extension error:
source_suffix '.ipynb' is already registered
```

Also described here: https://github.com/executablebooks/jupyter-book/issues/1344#issuecomment-1062544017

Offending line is presumably: https://github.com/jupyterlite/jupyterlite-sphinx/blob/f14181aac6772b285f0dbd8616c33a5db742c3c7/src/jupyterlite_sphinx.py#L274

**Comment by martinRenou** [comment]
Thanks for reporting. I wonder what should be done for fixing this.

We could either use the `override` option (see https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_source_suffix) to force using jupyterlite-sphinx suffix handlers, or we could back off if it's already registered.

I guess the second option is best. The end user can override that in their configuration anyway (see https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix).

So maybe something like 
```python
try:
    app.add_source_suffix(".ipynb", "jupyterlite_notebook")
catch ExtensionError:
    # Show a warning explaining how to force "jupyterlite_notebook"?
    pass
```

**Comment by psychemedia** [comment]
Yeah, I was wondering if there was a way of looking up already registered source suffixes, other than raising an exception if you try to re-add one, but I can't spot anything from a quick look at the docs.

The `override` option is new to me (I wonder if there are any side effects from re-registering a suffix?).

**Comment by martinRenou** [comment]
Looking at [the Sphinx code](https://github.com/sphinx-doc/sphinx/blob/f38bd8e9529d50e5cceffe3ca55be4b758529ff7/sphinx/registry.py#L268), we could probably do:

```python
if '.ipynb' not in self.app.registry.source_suffix:
    app.add_source_suffix(".ipynb", "jupyterlite_notebook")
else:
    # Show a warning explaining how to force "jupyterlite_notebook"?
    pass
```

**Comment by martinRenou** [comment]
We can also probably do just like nbsphinx does https://github.com/spatialaudio/nbsphinx/blob/64cd5a4ddadc8fb03887f3fac821cdfd184d6246/src/nbsphinx.py#L1889-L1890

**Comment by martinRenou** [comment]
Actually what nbsphinx does does not work and collide with jupyterlite-sphinx, so I guess my proposition above is safer.
