### ISSUE TITLE
Docs failing to serve the lite IFrames

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite-sphinx#34]
## Description

https://jupyterlite-sphinx.readthedocs.io/ is currently showing 404 issues that were not happening on the latest PR https://jupyterlite-sphinx--32.org.readthedocs.build/en/32/

There might be an issue with the `src` of the IFrames but I have troubles understanding what is the issue exactly.

cc. @psychemedia

**Comment by psychemedia** [comment]
I note you had changed iframe paths in https://github.com/jupyterlite/jupyterlite-sphinx/commit/954874086b493af5b9c244e780822b30e05354d9 ?
