### ISSUE TITLE
Should jupyterlite-sphinx be able to render for local Sphinx builds?

### ISSUE THREAD

**Issue by matthewfeickert** [jupyterlite/jupyterlite-sphinx#37]
Hi. Thanks for making `jupyterlite-sphinx` and for the very nice [Jupyter Everywhere](https://blog.jupyter.org/jupyter-everywhere-f8151c2cc6e8) blog post today. :+1: I don't think I have a bug, but just a misunderstanding so I opened up a blank Issue (if you think this should be a bug report just let me know and I'll transfer it).

After reading the blog post I tried to see how this might look for `pyhf` by adding both an iframe (which works!) to the README and also by using the `jupyterlite-sphinx` `replite` environment.

```diff
diff --git a/README.rst b/README.rst
index 07fe617c..7a29ee36 100644
--- a/README.rst
+++ b/README.rst
@@ -32,6 +32,32 @@ to support modern computational graph libraries such as PyTorch and
 TensorFlow in order to make use of features such as autodifferentiation
 and GPU acceleration.
 
+Try out now with Pyolite
+------------------------
+
+.. raw:: html
+
+   <iframe
+      src="https://jupyterlite.github.io/demo/repl/index.html?kernel=python&toolbar=1&code=import%20micropip%0Aawait%20micropip.install%28%5B%22pyhf%3D%3D0.6.3%22%2C%20%22requests%22%5D%29%0Aimport%20pyhf"
+      width="100%"
+      height="500px"
+   ></iframe>
+
+Example using jupyterlite-sphinx
+--------------------------------
+
+.. replite::
+   :kernel: python
+   :toolbar: 1
+   :theme: JupyterLab Light
+   :width: 100%
+   :height: 600px
+
+    print('Hello from a JupyterLite console!')
+    import micropip
+    await micropip.install(["pyhf==0.6.3", "requests"])
+    import pyhf
+
 User Guide
 ----------
 
diff --git a/docs/conf.py b/docs/conf.py
index 642bf1fc..f7f9b60f 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -53,6 +53,7 @@ def setup(app):
     'sphinx_issues',
     'sphinx_copybutton',
     'xref',
+    'jupyterlite_sphinx',
 ]
 bibtex_bibfiles = [
     "bib/docs.bib",
diff --git a/setup.py b/setup.py
index 9fb006ae..e689d29a 100644
--- a/setup.py
+++ b/setup.py
@@ -58,6 +58,7 @@
             'ipywidgets',
             'sphinx-issues',
             'sphinx-copybutton>=0.3.2',
+            'jupyterlite-sphinx>=0.4.4',
         ]
     )
 )
```

### Local build

When I [build the docs locally](https://github.com/scikit-hep/pyhf/blob/f862b8cabb87ed32dd3e747467f629b8839a66ad/.github/workflows/docs.yml#L57-L58) with Sphinx, the `iframe` works (of course) but I don't see any output from the `jupyterlite-sphinx` segment.

![locally](https://user-images.githubusercontent.com/5142394/158474920-3bbaaa6b-ee95-4618-91f8-f983fa9cb7ec.png)

### ReadTheDocs build

If I have ReadTheDocs do a build on the branch that I have this code in though, it at least shows the render, but then fails to execute multiple lines.

![read_the_docs_fail](https://user-images.githubusercontent.com/5142394/158477252-c4cac568-7a02-45e9-8c7e-bc7c9fdf5686.png)

Are there things that I should be doing differently with the Sphinx build to get the `jupyterlite-sphinx` component to render locally? Does `jupyterlite-sphinx` allow for multiple lines of input to be given in the `replite` environment?

## Related Issues

* https://github.com/scikit-hep/pyhf/issues/1775

**Comment by martinRenou** [comment]
Thanks for opening an issue :)

> When I [build the docs locally](https://github.com/scikit-hep/pyhf/blob/f862b8cabb87ed32dd3e747467f629b8839a66ad/.github/workflows/docs.yml#L57-L58) with Sphinx, the iframe works (of course) but I don't see any output from the jupyterlite-sphinx segment.

How are you looking at the docs locally? If you open the output HTML file with your browser it might not work indeed, you should probably **serve the output docs** with a simple server: `python -m http.server` from the built directory.

> Does jupyterlite-sphinx allow for multiple lines of input to be given in the replite environment?

It does since a couple of days ago https://github.com/jupyterlite/jupyterlite-sphinx/pull/30, but there might be an issue in your case. I'll tag this as a bug.

My commit might not be super great, we should find a way to cleanup the URL properly (probably with `urllib.parse`).

**Comment by matthewfeickert** [comment]
> How are you looking at the docs locally? If you open the output HTML file with your browser it might not work indeed, you should probably **serve the output docs** with a simple server: `python -m http.server` from the built directory.

Ah thanks for pointing this out. Indeed, I was just opening the built docs in a browser, but now running `python -m http.server` inside of the built output directory (`_build/html`) has things working visually. :+1: 

![serve_working](https://user-images.githubusercontent.com/5142394/158547492-dacdc6cc-07a3-450e-a025-878869606a07.png)


> > Does jupyterlite-sphinx allow for multiple lines of input to be given in the replite environment?
> 
> It does since a couple of days ago #30, but there might be an issue in your case. I'll tag this as a bug.
> 
> My commit might not be super great, we should find a way to cleanup the URL properly (probably with `urllib.parse`).

Hm. I'm able to reproduce your working examples from PR #30 (as expected)

![working_example](https://user-images.githubusercontent.com/5142394/158548123-ccfc3c2d-a03c-49c0-ba07-3596904bea2a.png)

but interestingly enough the problem seems(?) to be the quote type that is used. My new minimal failing example is just to use double quotes

```rst
.. replite::
   :kernel: python
   :toolbar: 1
   :theme: JupyterLab Light
   :width: 100%
   :height: 600px

    print("Hello from a JupyterLite console!")
```

![double_quote_fail](https://user-images.githubusercontent.com/5142394/158550425-c06a7db8-4bba-4d3e-8d64-df4f077eecff.png)


If I use single quotes for strings then I'm almost able to get a full example to work, but here the `+` isn't getting escaped correctly or something as it fails

```rst
.. replite::
   :kernel: python
   :toolbar: 1
   :theme: JupyterLab Light
   :width: 100%
   :height: 600px

    print('Hello from a JupyterLite console!')

    import micropip
    await micropip.install(['pyhf==0.6.3', 'requests'])
    import pyhf

    pyhf.set_backend('numpy')
    model = pyhf.simplemodels.uncorrelated_background(
       signal=[12.0, 11.0], bkg=[50.0, 52.0], bkg_uncertainty=[3.0, 7.0]
    )
    data = [51, 48] + model.config.auxdata
    test_mu = 1.0
    CLs_obs, CLs_exp = pyhf.infer.hypotest(
       test_mu, data, model, test_stat='qtilde', return_expected=True
    )
    print(f'Observed: {CLs_obs:.8f}, Expected: {CLs_exp:.8f}')
```

![plus_missing](https://user-images.githubusercontent.com/5142394/158549870-7a024fca-c823-4585-ac06-3915743351dd.png)

**Comment by matthewfeickert** [comment]
At this point I'll also mention some some relevant things for my virtual environment I'm doing this all in on my Ubuntu machine

```console
$ python --version --version
Python 3.9.6 (default, Jul 20 2021, 02:29:54) 
[GCC 9.3.0]
$ python -m pip list | grep jupyterlite-sphinx
jupyterlite-sphinx                0.4.4
$ python -m pip list | grep 'jupyter\|Sphinx'
jupyter                           1.0.0
jupyter-client                    6.1.12
jupyter-console                   6.4.0
jupyter-core                      4.8.1
jupyter-server                    1.11.1
jupyter-server-mathjax            0.2.3
jupyterlab                        3.2.0
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.8.2
jupyterlab-widgets                1.0.2
jupyterlite                       0.1.0b2
jupyterlite-sphinx                0.4.4
Sphinx                            4.3.2
```

**Comment by martinRenou** [comment]
> If I use single quotes for strings then I'm almost able to get a full example to work

😆 yeah, we might need to escape quotes from the code in the URL

**Comment by martinRenou** [comment]
@matthewfeickert I pushed a PR to cleanup the query options in the URL https://github.com/jupyterlite/jupyterlite-sphinx/pull/41

This should hopefully address your issue

**Comment by martinRenou** [comment]
![test](https://user-images.githubusercontent.com/21197331/160432801-8de9545b-ab1c-4aba-8127-feb112c006fd.png)

**Comment by martinRenou** [comment]
Thanks again for reporting!

**Comment by matthewfeickert** [comment]
> I pushed a PR to cleanup the query options in the URL #41
> 
> This should hopefully address your issue

Fantastic! Thank you so much for this effort @martinRenou &mdash; truly appreciated.

From the screenshot above it seems that things are functional. :+1: On a much more minor note, it seems that it is eating white space though as

```python
model = pyhf.simplemodels.uncorrelated_background(
   signal=[12.0, 11.0], bkg=[50.0, 52.0], bkg_uncertainty=[3.0, 7.0]
)
```

is coming out with the white space before `signal` eaten

```python
model = pyhf.simplemodels.uncorrelated_background(
signal=[12.0, 11.0], bkg=[50.0, 52.0], bkg_uncertainty=[3.0, 7.0]
)
```

This won't cause any problems for the time being, but is perhaps interesting to note.

**Comment by martinRenou** [comment]
Fixing it in https://github.com/jupyterlite/jupyterlite-sphinx/pull/42

**Comment by matthewfeickert** [comment]
> Fixing it in #42

Awesome thanks! `v0.4.6` is looking great. :sunglasses:
