### ISSUE TITLE
all.json and files/ don't always get created

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite-sphinx#38]
I'm seeing an intermittent issue (that I haven't been able to pin down as yet) whereby notebook files are not copied over to a `lite/files` directory and no `all.json` manifest file detailing the files is produced. (I'm not sure if it's a sphinx related thing, whereby sphinx thinks the files don't need copying over?)

**Comment by psychemedia** [comment]
So I'm guessing it's something to do with how https://github.com/jupyterlite/jupyterlite-sphinx/blob/b0e17a9cba36911c12619dc0a8c80a1571e3adac/src/jupyterlite_sphinx.py#L160 hooks up, or doesn't...

**Comment by martinRenou** [comment]
> I'm seeing an intermittent issue (that I haven't been able to pin down as yet) whereby notebook files are not copied over to a lite/files directory and no all.json manifest file detailing the files is produced. (I'm not sure if it's a sphinx related thing, whereby sphinx thinks the files don't need copying over?)

Could you provide the logs of the sphinx build? There might be some information there.

> So I'm guessing it's something to do with how  [...] `def run(self):` [...] hooks up, or doesn't...

I believe that's unlikely, the directive has somewhat nothing to do with the jupyterlite build step. The only thing that I see could happen with the directive is the Notebook files not being copied in the right place for the jupyterlite cli to find.

**Comment by psychemedia** [comment]
Ah... I think I see what it is.

I am using `jupyterlite-sphinx` in a Jupyter Book context so that I can launch a page into a JupyterLite environment:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/82988/159446749-26ed24d0-f933-4157-9a51-36e9f23d99d6.png">

So I'm not actually embedding any notebooks in pages unless I manually create and populate a `_contents` (`CONTENT_DIR`) directory myself.

What I was expecting from a `jupyterlite-sphinx` extension was to be able to create a JupyterLite environment containing all included notebook executable files parsed by sphinx (which I use to create my Jupyter Book pages, for example). That is, if sphinx thinks it's a valid (non-excluded) executable file, so should `jupyterlite-sphinx`.

I can see this might work best as an optional config setting: in some cases you might only want to copy over files that are used in embedded iframes.

I also note that there may be cases where you want to include other files in the jupyterlite distribution, for example, image files or data files.

**Comment by martinRenou** [comment]
jupyterlite-sphinx defaults to building jupyterlite in a temporary dir, it will discard any file from your docs. Hopefully you should soon be able to change the config either passing a content option: https://github.com/jupyterlite/jupyterlite-sphinx/pull/24 (not merged yet) or changing the build dir https://github.com/jupyterlite/jupyterlite-sphinx/pull/16 (also not merged).
