### ISSUE TITLE
bqplot example in configuration docs is broken

### ISSUE THREAD

**Issue by horaceg** [jupyterlite/jupyterlite-sphinx#39]
## Description

When running the example notebook in https://jupyterlite-sphinx.readthedocs.io/en/latest/configuration.html, I get the following:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/12616944/160395431-1aea53bc-976b-4762-ac37-c5f6657295ae.png">

```python
ValueError: Requested 'widgetsnbextension~=3.6.0', but widgetsnbextension==3.5.0 is already installed
```

I am especially interested in this since I am trying to use bqplot for my project also, that's why I visited the page actually

## Reproduce

1. Go to https://jupyterlite-sphinx.readthedocs.io/en/latest/configuration.html
2. Click on run all
3. Scroll down to the first cell
```python
ValueError: Requested 'widgetsnbextension~=3.6.0', but widgetsnbextension==3.5.0 is already installed
```

## Context

- JupyterLite version:
- Operating System and version: MacOS 12.1
- Browser and version: Chrome 99

<details><summary>Browser Output</summary>
<pre>
index.es6.js:288 Plugin '@jupyterlab/drawio-extension:plugin' failed to activate.
(anonymous) @ index.es6.js:288
Promise.catch (async)
(anonymous) @ index.es6.js:287
e.start @ index.es6.js:286
(anonymous) @ index.js:306
await in (anonymous) (async)
86798 @ index.js:310
v @ bootstrap:19
Promise.then (async)
(anonymous) @ bootstrap.js:90
await in (anonymous) (async)
20514 @ bootstrap.js:64
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=75b8d6e:1
index.es6.js:289 Error: No provider for: @jupyterlab/application:ILayoutRestorer.
    at f.e.resolveRequiredService (index.es6.js:201:35)
    at index.es6.js:156:70
    at Array.map (<anonymous>)
    at f.e.activatePlugin (index.es6.js:156:38)
    at index.es6.js:287:26
    at Array.map (<anonymous>)
    at f.e.start (index.es6.js:286:33)
    at index.js:306:13
</pre>
</details>

**Comment by martinRenou** [comment]
Thanks for reporting! We probably need to update the configuration https://github.com/jupyterlite/jupyterlite-sphinx/blob/main/docs/jupyterlite_config.json

**Comment by martinRenou** [comment]
Rebuilding the docs with the latest jupyterlite version fixed it https://jupyterlite-sphinx.readthedocs.io/en/latest/configuration.html thanks again for reporting!
