### ISSUE TITLE
Building docs does not include notebook files in the jupyterlite contents

### ISSUE THREAD

**Issue by jasongrout** [jupyterlite/jupyterlite-sphinx#53]
## Description

When I use jupyterlite-sphinx to build its own docs, no files show up in the jlab or notebook contents (e.g., bqplot.ipynb or my_notebook.ipynb are not available to lab, the file tree just shows no documents available). This causes errors, for example, the bqplot example just shows a 404 error for loading bqplot:

<img width="740" alt="Screen Shot 2022-06-16 at 11 38 24" src="https://user-images.githubusercontent.com/192614/174132638-007e6df5-4a54-495a-9862-4a6d94b8a40a.png">

I get similar results when trying to build the docs for ipyleaflet and when trying to incorporate jupyterlite-sphinx in ipywidgets.

## Reproduce

1. Clone jupyterlite-sphinx
2. create a new environment and pip install -e jupyterlite-sphinx
3. Go to the docs directory and build the documentation

I put in a number of debugging statements. The notebooks seem to be correctly copied to the `_contents` directory, and the jupyterlite build command is  `['jupyter', 'lite', 'build', '--debug', '--config', 'jupyterlite_config.json', '--lite-dir', '/var/folders/l0/km7g2yss183d7nrskwl4xgbc0000gn/T/tmpf_glbv82', '--contents', '/Users/jason/projects/jupyterlite-sphinx/docs/_contents', '--output-dir', '/Users/jason/projects/jupyterlite-sphinx/docs/build/lite']`, and in the jupyterlite build output, I see 
```
[LiteBuildApp] [lite] [contents] All Contents ['/Users/jason/projects/jupyterlite-sphinx/docs/_contents/my_notebook.ipynb',
 '/Users/jason/projects/jupyterlite-sphinx/docs/_contents/bqplot.ipynb']
```
However, I still don't see notebook files in the embedded jupyterlite iframes.

I do notice there is no `lite/api` directory:

```
$ ls build/lite/ | cat
bootstrap.js
build
config-utils.js
doc
index.html
jupyter-lite.ipynb
jupyter-lite.json
jupyterlite.schema.v0.json
kernelspecs
lab
package.json
piplite.schema.v0.json
repl
retro
tree
```
and the browser gets a 404 when it requests `http://localhost:8000/lite/api/contents/all.json`

## Expected behavior

See the bqplot and my_notebook notebook files in jupyterlite jlab.

## Context

- JupyterLite version: 0.1.0b8
- Operating System and version: MacOS 12.4, m1 processor if that makes a difference
- Browser and version: Firefox 101

<details><summary>Browser Output</summary>
<pre>
XHRGEThttp://localhost:8000/lite/api/translations/en.json
[HTTP/1.0 404 File not found 3ms]

XHRGEThttp://localhost:8000/lite/api/translations/all.json
[HTTP/1.0 404 File not found 2ms]

XHRGEThttp://localhost:8000/lite/api/contents/all.json
[HTTP/1.0 404 File not found 2ms]

XHRGEThttp://localhost:8000/lite/api/contents/all.json
[HTTP/1.0 404 File not found 1ms]

</pre>
<img width="1261" alt="Screen Shot 2022-06-16 at 11 47 17" src="https://user-images.githubusercontent.com/192614/174133968-6a0fa58c-52b2-4d13-ab26-b3d46a3733b5.png">

</details>

**Comment by jasongrout** [comment]
When I try to run jupyterlite by itself (after commenting out the code that deletes the _contents directory so it stays around), I get a 404 error when fetching the bqplot federated extension: `TaskError - taskid:post_init:federated_extensions:fetch:bqplot-0.12.33-pyhd8ed1ab_0.tar.bz2
`

Indeed, looking at the config file, I see that the first federated extension listed is https://github.com/conda-forge/releases/releases/download/noarch/bqplot-0.12.33-pyhd8ed1ab_0.tar.bz2/bqplot-0.12.33-pyhd8ed1ab_0.tar.bz2, but that URL gives a 404.

**Comment by jasongrout** [comment]
Actually, I see the same 404 error on the docs automatically built for https://github.com/jupyterlite/jupyterlite-sphinx/pull/52: https://jupyterlite-sphinx--52.org.readthedocs.build/en/52/configuration.html

**Comment by martinRenou** [comment]
Thanks for reporting! I suspect it's a relatively new issue. I saw this issue when building some docs and thought it was related to jupyterlite-xeus-python.. I recall seeing some diff on the jupyterlite repo that was changing a link, I'll try to find this again.
