### ISSUE TITLE
add_source_suffix messes with sphinx-gallery

### ISSUE THREAD

**Issue by amueller** [jupyterlite/jupyterlite-sphinx#65]
Doing
``python
app.add_source_suffix(".ipynb", "jupyterlite_notebook")
``
generates a lot of warning when combined with sphinx-gallery, as it means there are multiple possible files for each reference.
It doesn't seem to be necessary, though, everything works if I comment it out?

**Comment by martinRenou** [comment]
Thanks for trying jupyterlite-sphinx :)

I've seen conflicts between this sphinx plugin and others like nbsphinx which were adding the same source prefix. I pushed a fix in nbsphinx here https://github.com/spatialaudio/nbsphinx/pull/637

Are you using nbsphinx there? If yes. You might want to specify nbsphinx before jupyterlite-sphinx in the `conf.py`:
```python
extensions = [
    'nbsphinx',
    'jupyterlite_sphinx',
]
```

> It doesn't seem to be necessary, though, everything works if I comment it out?

Indeed it works without this in most cases. Removing it removes the ability to use jupyterlite-sphinx for loading Notebooks as "docs source" in the doctree.

**Comment by martinRenou** [comment]
Actually, I feel like you are facing the same issue I'm facing in https://github.com/matplotlib/matplotlib/pull/22634 where I see many warnings like:
```
WARNING: multiple files found for the document "gallery/animation/animate_decay": ['gallery/animation/animate_decay.py', 'gallery/animation/animate_decay.py.md5', 'gallery/animation/animate_decay.rst', 'gallery/animation/animate_decay.ipynb']
Use '/home/circleci/project/doc/gallery/animation/animate_decay.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/animated_histogram": ['gallery/animation/animated_histogram.py', 'gallery/animation/animated_histogram.py.md5', 'gallery/animation/animated_histogram.rst', 'gallery/animation/animated_histogram.ipynb']
Use '/home/circleci/project/doc/gallery/animation/animated_histogram.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/animation_demo": ['gallery/animation/animation_demo.py', 'gallery/animation/animation_demo.py.md5', 'gallery/animation/animation_demo.rst', 'gallery/animation/animation_demo.ipynb']
Use '/home/circleci/project/doc/gallery/animation/animation_demo.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/bayes_update": ['gallery/animation/bayes_update.py', 'gallery/animation/bayes_update.py.md5', 'gallery/animation/bayes_update.rst', 'gallery/animation/bayes_update.ipynb']
Use '/home/circleci/project/doc/gallery/animation/bayes_update.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/unchained": ['gallery/animation/unchained.py.md5', 'gallery/animation/unchained.ipynb', 'gallery/animation/unchained.rst', 'gallery/animation/unchained.py']
Use '/home/circleci/project/doc/gallery/animation/unchained.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/double_pendulum": ['gallery/animation/double_pendulum.py', 'gallery/animation/double_pendulum.py.md5', 'gallery/animation/double_pendulum.rst', 'gallery/animation/double_pendulum.ipynb']
Use '/home/circleci/project/doc/gallery/animation/double_pendulum.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/dynamic_image": ['gallery/animation/dynamic_image.py', 'gallery/animation/dynamic_image.py.md5', 'gallery/animation/dynamic_image.rst', 'gallery/animation/dynamic_image.ipynb']
Use '/home/circleci/project/doc/gallery/animation/dynamic_image.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/frame_grabbing_sgskip": ['gallery/animation/frame_grabbing_sgskip.py', 'gallery/animation/frame_grabbing_sgskip.rst', 'gallery/animation/frame_grabbing_sgskip.ipynb']
Use '/home/circleci/project/doc/gallery/animation/frame_grabbing_sgskip.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/pause_resume": ['gallery/animation/pause_resume.py', 'gallery/animation/pause_resume.py.md5', 'gallery/animation/pause_resume.rst', 'gallery/animation/pause_resume.ipynb']
Use '/home/circleci/project/doc/gallery/animation/pause_resume.rst' for the build.
WARNING: multiple files found for the document "gallery/animation/rain": ['gallery/animation/rain.py', 'gallery/animation/rain.py.md5', 'gallery/animation/rain.rst', 'gallery/animation/rain.ipynb']
```
is it what you are seeing?

In this case you can discard what I said earlier, it's probably unrelated. I have no clue why this is happening.

On a last resort, we can probably add a config option for jupyterlite-sphinx that would make it not call `python app.add_source_suffix(".ipynb", "jupyterlite_notebook")`.

**Comment by martinRenou** [comment]
I pushed a PR to make the source suffix binding optional https://github.com/jupyterlite/jupyterlite-sphinx/pull/66 in jupyterlite-sphinx.

It might be a good idea to modify sphinx-gallery so that it's more specific about which source file it wants to add in the doctree (*e.g.* `gallery/animation/rain.rst` instead of `gallery/animation/rain`). That way it will work with any other sphinx plugin that register the `.ipynb` suffix (I'm thinking of nbsphinx).

**Comment by amueller** [comment]
Hey! Yes I think you characterized the issue correctly. And thanks for the PR! I agree it would be good to be more specific in sphinx-gallery as well. I'll look into that. But providing an opt-out is a good work-around that might also help others.
